package fyi.pauli.solembum.networking.packet.outgoing.login

import kotlinx.serialization.Serializable

/**
 * Packet, used to authenticate the server.
 *
 * @param serverId Appears to be empty.
 * @param publicKey The server's public key, in bytes.
 * @param verifyToken A sequence of random bytes generated by the server.
 */
@Serializable
public data class EncryptionRequest(
	var serverId: String, var publicKey: ByteArray, var verifyToken: ByteArray,
) : fyi.pauli.solembum.networking.packet.outgoing.OutgoingPacket() {
	override fun equals(other: Any?): Boolean {
		if (this === other) return true
		if (other == null || this::class != other::class) return false

		other as fyi.pauli.solembum.networking.packet.outgoing.login.EncryptionRequest

		if (serverId != other.serverId) return false
		if (!publicKey.contentEquals(other.publicKey)) return false
		if (!verifyToken.contentEquals(other.verifyToken)) return false

		return true
	}

	override fun hashCode(): Int {
		var result = serverId.hashCode()
		result = 31 * result + publicKey.contentHashCode()
		result = 31 * result + verifyToken.contentHashCode()
		return result
	}

	override val id: Int
		get() = 0x01

	override val state: fyi.pauli.solembum.networking.packet.State
		get() = _root_ide_package_.fyi.pauli.solembum.networking.packet.State.LOGIN
	override val debugName: String
		get() = "Encryption Request"
}