on:
  push:
    branches:
      - publish
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Publish
        run: ./gradlew publishAllPublicationsToPauliRepository --no-daemon -PpauliUsername=${{ secrets.PAULI_REPOSITORY_USERNAME }} -PpauliPassword=${{ secrets.PAULI_REPOSITORY_PASSWORD }}
